[package]
name = "rpn"
version = "0.1.0"
authors = ["Florent FAYOLLE <florent.fayolle69@gmail.com>"]
license = "MIT"
description = "A Reverse Polish Notation lib + executable"

[dependencies]
permutohedron = "0.2.4"
rand = "*"

[[bin]]
name = "rpn"
doc = false
path = "src/main.rs"
